import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                tabIndex={-1}
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            ><div className="mt-5 ml-5 text-3xl">Part Mag</div>
                <hr className="mt-5 border-primary" />
                {children}
            </body>
        </html>
    );
}
